export { default as addToFirestore } from './functions/addToFirestore'
export { default as changeDocId } from './functions/changeDocId'
export { default as copyCollection } from './functions/copyCollection'
export { default as deleteEntireCollection } from './functions/deleteEntireCollection'
export { default as queryFirestore } from './functions/queryFirestore'
export { default as setToFirestore } from './functions/setToFirestore'
export { default as unwrapFirestoreDoc } from './functions/unwrapFirestoreDoc'
